### ISSUE TITLE
Problem with the font: font not found - can't compile..

### ISSUE THREAD

**Issue by kylak** [raphink/geneve_1564#3]
Hello

I can't compile the files documents: 
> geneve_1564_modern.tex
> geneve_1564.tex

_I have the following error:_
<img width="427" alt="capture d ecran 2018-12-12 a 14 57 38" src="https://user-images.githubusercontent.com/16438248/49874495-edfc2980-fe1e-11e8-8f53-ee5b63c117a0.png">

(I have the same problem with geneve_1564_modern.tex at line 18.)
Je parle français aussi (je suis français et crois en Jésus-Christ), et je trouve l'idée super !

**Comment by raphink** [comment]
Hello,

Are you trying to compile using the Makefile, or with a manual command?

**Comment by raphink** [comment]
Concernant l'idée, j'aurais aimé faire une version complète pour les 500 ans de la réforme, mais le boulot était trop important pour le faire seul :cry:

**Comment by kylak** [comment]
I'm trying to compile using the makefile command (called "Composer" on my TeXShop)
Est-ce que cette bible existe dans un format texte ou seulement en scan au quel cas devons-nous recopier à la main ce que nous lisons sur le scan ?

**Comment by raphink** [comment]
À ma connaissance seulement en scan. Je n'ai jamais trouvé de version texte.

**Comment by kylak** [comment]
D'accord merci

**Comment by raphink** [comment]
@kylak est-ce que le problème de police était corrigé?

**Comment by kylak** [comment]
Shalom, je viens de cloner le repository et essayer de composer à nouveau, mais le problème de police persiste pour les deux fichiers tex.

**Comment by raphink** [comment]
En lançant `make` ?

**Comment by kylak** [comment]
Oui.
